package shared

type DimensionEnum string

const (
	DimensionEnumAsn                      DimensionEnum = "asn"
	DimensionEnumBrowser                  DimensionEnum = "browser"
	DimensionEnumBrowserVersion           DimensionEnum = "browser_version"
	DimensionEnumCdn                      DimensionEnum = "cdn"
	DimensionEnumContinentCode            DimensionEnum = "continent_code"
	DimensionEnumCountry                  DimensionEnum = "country"
	DimensionEnumExitBeforeVideoStart     DimensionEnum = "exit_before_video_start"
	DimensionEnumExperimentName           DimensionEnum = "experiment_name"
	DimensionEnumOperatingSystem          DimensionEnum = "operating_system"
	DimensionEnumOperatingSystemVersion   DimensionEnum = "operating_system_version"
	DimensionEnumPlayerAutoplay           DimensionEnum = "player_autoplay"
	DimensionEnumPlayerErrorCode          DimensionEnum = "player_error_code"
	DimensionEnumPlayerMuxPluginName      DimensionEnum = "player_mux_plugin_name"
	DimensionEnumPlayerMuxPluginVersion   DimensionEnum = "player_mux_plugin_version"
	DimensionEnumPlayerName               DimensionEnum = "player_name"
	DimensionEnumPlayerPreload            DimensionEnum = "player_preload"
	DimensionEnumPlayerRemotePlayed       DimensionEnum = "player_remote_played"
	DimensionEnumPlayerSoftware           DimensionEnum = "player_software"
	DimensionEnumPlayerSoftwareVersion    DimensionEnum = "player_software_version"
	DimensionEnumPlayerVersion            DimensionEnum = "player_version"
	DimensionEnumPrerollAdAssetHostname   DimensionEnum = "preroll_ad_asset_hostname"
	DimensionEnumPrerollAdTagHostname     DimensionEnum = "preroll_ad_tag_hostname"
	DimensionEnumPrerollPlayed            DimensionEnum = "preroll_played"
	DimensionEnumPrerollRequested         DimensionEnum = "preroll_requested"
	DimensionEnumRegion                   DimensionEnum = "region"
	DimensionEnumSourceHostname           DimensionEnum = "source_hostname"
	DimensionEnumSourceType               DimensionEnum = "source_type"
	DimensionEnumStreamType               DimensionEnum = "stream_type"
	DimensionEnumSubPropertyID            DimensionEnum = "sub_property_id"
	DimensionEnumVideoEncodingVariant     DimensionEnum = "video_encoding_variant"
	DimensionEnumVideoID                  DimensionEnum = "video_id"
	DimensionEnumVideoSeries              DimensionEnum = "video_series"
	DimensionEnumVideoTitle               DimensionEnum = "video_title"
	DimensionEnumViewSessionID            DimensionEnum = "view_session_id"
	DimensionEnumViewerConnectionType     DimensionEnum = "viewer_connection_type"
	DimensionEnumViewerDeviceCategory     DimensionEnum = "viewer_device_category"
	DimensionEnumViewerDeviceManufacturer DimensionEnum = "viewer_device_manufacturer"
	DimensionEnumViewerDeviceModel        DimensionEnum = "viewer_device_model"
	DimensionEnumViewerDeviceName         DimensionEnum = "viewer_device_name"
	DimensionEnumViewerUserID             DimensionEnum = "viewer_user_id"
)
