package shared

type VideoView struct {
	Asn                            *int64           `json:"asn,omitempty"`
	AsnName                        *string          `json:"asn_name,omitempty"`
	BufferingCount                 *int64           `json:"buffering_count,omitempty"`
	BufferingDuration              *int64           `json:"buffering_duration,omitempty"`
	BufferingRate                  *string          `json:"buffering_rate,omitempty"`
	Cdn                            *string          `json:"cdn,omitempty"`
	City                           *string          `json:"city,omitempty"`
	ContinentCode                  *string          `json:"continent_code,omitempty"`
	CountryCode                    *string          `json:"country_code,omitempty"`
	CountryName                    *string          `json:"country_name,omitempty"`
	Custom1                        *string          `json:"custom_1,omitempty"`
	Custom2                        *string          `json:"custom_2,omitempty"`
	Custom3                        *string          `json:"custom_3,omitempty"`
	Custom4                        *string          `json:"custom_4,omitempty"`
	Custom5                        *string          `json:"custom_5,omitempty"`
	ErrorTypeID                    *int             `json:"error_type_id,omitempty"`
	Events                         []VideoViewEvent `json:"events,omitempty"`
	ExitBeforeVideoStart           *bool            `json:"exit_before_video_start,omitempty"`
	ExperimentName                 *string          `json:"experiment_name,omitempty"`
	ID                             *string          `json:"id,omitempty"`
	InsertedAt                     *string          `json:"inserted_at,omitempty"`
	Isp                            *string          `json:"isp,omitempty"`
	Latitude                       *string          `json:"latitude,omitempty"`
	Longitude                      *string          `json:"longitude,omitempty"`
	Metro                          *string          `json:"metro,omitempty"`
	MuxAPIVersion                  *string          `json:"mux_api_version,omitempty"`
	MuxEmbedVersion                *string          `json:"mux_embed_version,omitempty"`
	MuxViewerID                    *string          `json:"mux_viewer_id,omitempty"`
	PageLoadTime                   *int64           `json:"page_load_time,omitempty"`
	PageType                       *string          `json:"page_type,omitempty"`
	PageURL                        *string          `json:"page_url,omitempty"`
	PlatformDescription            *string          `json:"platform_description,omitempty"`
	PlatformSummary                *string          `json:"platform_summary,omitempty"`
	PlaybackScore                  *string          `json:"playback_score,omitempty"`
	PlayerAutoplay                 *bool            `json:"player_autoplay,omitempty"`
	PlayerErrorCode                *string          `json:"player_error_code,omitempty"`
	PlayerErrorMessage             *string          `json:"player_error_message,omitempty"`
	PlayerHeight                   *int             `json:"player_height,omitempty"`
	PlayerInstanceID               *string          `json:"player_instance_id,omitempty"`
	PlayerLanguage                 *string          `json:"player_language,omitempty"`
	PlayerLoadTime                 *int64           `json:"player_load_time,omitempty"`
	PlayerMuxPluginName            *string          `json:"player_mux_plugin_name,omitempty"`
	PlayerMuxPluginVersion         *string          `json:"player_mux_plugin_version,omitempty"`
	PlayerName                     *string          `json:"player_name,omitempty"`
	PlayerPoster                   *string          `json:"player_poster,omitempty"`
	PlayerPreload                  *bool            `json:"player_preload,omitempty"`
	PlayerRemotePlayed             *bool            `json:"player_remote_played,omitempty"`
	PlayerSoftware                 *string          `json:"player_software,omitempty"`
	PlayerSoftwareVersion          *string          `json:"player_software_version,omitempty"`
	PlayerSourceDomain             *string          `json:"player_source_domain,omitempty"`
	PlayerSourceDuration           *int64           `json:"player_source_duration,omitempty"`
	PlayerSourceHeight             *int             `json:"player_source_height,omitempty"`
	PlayerSourceHostName           *string          `json:"player_source_host_name,omitempty"`
	PlayerSourceStreamType         *string          `json:"player_source_stream_type,omitempty"`
	PlayerSourceType               *string          `json:"player_source_type,omitempty"`
	PlayerSourceURL                *string          `json:"player_source_url,omitempty"`
	PlayerSourceWidth              *int             `json:"player_source_width,omitempty"`
	PlayerStartupTime              *int64           `json:"player_startup_time,omitempty"`
	PlayerVersion                  *string          `json:"player_version,omitempty"`
	PlayerViewCount                *int64           `json:"player_view_count,omitempty"`
	PlayerWidth                    *int             `json:"player_width,omitempty"`
	PrerollAdAssetHostname         *string          `json:"preroll_ad_asset_hostname,omitempty"`
	PrerollAdTagHostname           *string          `json:"preroll_ad_tag_hostname,omitempty"`
	PrerollPlayed                  *bool            `json:"preroll_played,omitempty"`
	PrerollRequested               *bool            `json:"preroll_requested,omitempty"`
	PropertyID                     *int64           `json:"property_id,omitempty"`
	QualityScore                   *string          `json:"quality_score,omitempty"`
	RebufferPercentage             *string          `json:"rebuffer_percentage,omitempty"`
	RebufferingScore               *string          `json:"rebuffering_score,omitempty"`
	Region                         *string          `json:"region,omitempty"`
	RequestsForFirstPreroll        *int64           `json:"requests_for_first_preroll,omitempty"`
	SessionID                      *string          `json:"session_id,omitempty"`
	ShortTime                      *string          `json:"short_time,omitempty"`
	StartupScore                   *string          `json:"startup_score,omitempty"`
	SubPropertyID                  *string          `json:"sub_property_id,omitempty"`
	TimeToFirstFrame               *int64           `json:"time_to_first_frame,omitempty"`
	UpdatedAt                      *string          `json:"updated_at,omitempty"`
	UsedFullscreen                 *bool            `json:"used_fullscreen,omitempty"`
	VideoContentType               *string          `json:"video_content_type,omitempty"`
	VideoDuration                  *int64           `json:"video_duration,omitempty"`
	VideoEncodingVariant           *string          `json:"video_encoding_variant,omitempty"`
	VideoID                        *string          `json:"video_id,omitempty"`
	VideoLanguage                  *string          `json:"video_language,omitempty"`
	VideoProducer                  *string          `json:"video_producer,omitempty"`
	VideoSeries                    *string          `json:"video_series,omitempty"`
	VideoStartupPrerollLoadTime    *int64           `json:"video_startup_preroll_load_time,omitempty"`
	VideoStartupPrerollRequestTime *int64           `json:"video_startup_preroll_request_time,omitempty"`
	VideoStreamType                *string          `json:"video_stream_type,omitempty"`
	VideoTitle                     *string          `json:"video_title,omitempty"`
	VideoVariantID                 *string          `json:"video_variant_id,omitempty"`
	VideoVariantName               *string          `json:"video_variant_name,omitempty"`
	ViewAverageRequestLatency      *int64           `json:"view_average_request_latency,omitempty"`
	ViewAverageRequestThroughput   *int64           `json:"view_average_request_throughput,omitempty"`
	ViewEnd                        *string          `json:"view_end,omitempty"`
	ViewErrorID                    *int             `json:"view_error_id,omitempty"`
	ViewID                         *string          `json:"view_id,omitempty"`
	ViewMaxDownscalePercentage     *string          `json:"view_max_downscale_percentage,omitempty"`
	ViewMaxPlayheadPosition        *string          `json:"view_max_playhead_position,omitempty"`
	ViewMaxRequestLatency          *int64           `json:"view_max_request_latency,omitempty"`
	ViewMaxUpscalePercentage       *string          `json:"view_max_upscale_percentage,omitempty"`
	ViewPlayingTime                *string          `json:"view_playing_time,omitempty"`
	ViewSeekCount                  *int64           `json:"view_seek_count,omitempty"`
	ViewSeekDuration               *int64           `json:"view_seek_duration,omitempty"`
	ViewSessionID                  *string          `json:"view_session_id,omitempty"`
	ViewStart                      *string          `json:"view_start,omitempty"`
	ViewTotalContentPlaybackTime   *int64           `json:"view_total_content_playback_time,omitempty"`
	ViewTotalDownscaling           *string          `json:"view_total_downscaling,omitempty"`
	ViewTotalUpscaling             *string          `json:"view_total_upscaling,omitempty"`
	ViewerApplicationEngine        *string          `json:"viewer_application_engine,omitempty"`
	ViewerApplicationName          *string          `json:"viewer_application_name,omitempty"`
	ViewerApplicationVersion       *string          `json:"viewer_application_version,omitempty"`
	ViewerConnectionType           *string          `json:"viewer_connection_type,omitempty"`
	ViewerDeviceCategory           *string          `json:"viewer_device_category,omitempty"`
	ViewerDeviceManufacturer       *string          `json:"viewer_device_manufacturer,omitempty"`
	ViewerDeviceModel              *string          `json:"viewer_device_model,omitempty"`
	ViewerDeviceName               *string          `json:"viewer_device_name,omitempty"`
	ViewerExperienceScore          *string          `json:"viewer_experience_score,omitempty"`
	ViewerOsArchitecture           *string          `json:"viewer_os_architecture,omitempty"`
	ViewerOsFamily                 *string          `json:"viewer_os_family,omitempty"`
	ViewerOsVersion                *string          `json:"viewer_os_version,omitempty"`
	ViewerUserAgent                *string          `json:"viewer_user_agent,omitempty"`
	ViewerUserID                   *string          `json:"viewer_user_id,omitempty"`
	WatchTime                      *int64           `json:"watch_time,omitempty"`
	Watched                        *bool            `json:"watched,omitempty"`
	WeightedAverageBitrate         *int64           `json:"weighted_average_bitrate,omitempty"`
}
